### ISSUE TITLE
Document docker config

### ISSUE THREAD

**Issue by synfinatic** [synfinatic/udp-proxy-2020#136]
From the Roon community: https://community.roonlabs.com/t/how-i-got-roon-working-over-openvpn-hard-for-me-easy-for-you/122939/270 

```
version: '3.7'

services:
  udp-proxy:
    environment:
      - TZ=America/Los_Angeles
    image: synfinatic/udp-proxy-2020
    container_name: udp-proxy-2020
    restart: unless-stopped
    networks:
      macvlan_roon:
        ipv4_address: 192.168.50.49
      macvlan_main:
        ipv4_address: 192.168.20.48

    command: udp-proxy-2020 --port 9003 --interface eth0,eth1 --cache-ttl 300

networks:
    macvlan_roon:
      external: true
    macvlan_main:
      external: true
```
